server:
  port: 8089

spring:
  application:
    name: Job Search

  datasource:
    url: jdbc:h2:./db/job search;AUTO_SERVER=TRUE
    username: job
    password: search
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml